### ISSUE TITLE
Error when running test code

### ISSUE THREAD

**Issue by XenonLamb** [csm9493/FC-AIDE-Keras#2]
I ran the test_fc_aide_ft.py without any modification, but the following error occurs:
``
 tracking <tf.Variable 'naide__conv2d__q1_1/Variable:0' shape=(3, 3, 1, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e1_1/Variable:0' shape=(3, 3, 1, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n1_1/Variable:0' shape=(3, 3, 1, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_1/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_1/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_1/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_2/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_2/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_2/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_3/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_3/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_3/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_4/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_4/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_4/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_5/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_5/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_5/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_6/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_6/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_6/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_7/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_7/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_7/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_8/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_8/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_8/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_9/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_9/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_9/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_10/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_10/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_10/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_11/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_11/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_11/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_12/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_12/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_12/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_13/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_13/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_13/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_14/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_14/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_14/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_15/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_15/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_15/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_16/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_16/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_16/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_17/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_17/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_17/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_18/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_18/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_18/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_19/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_19/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_19/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_20/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_20/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_20/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__q2_21/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d__e2_21/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
tracking <tf.Variable 'naide__conv2d_dow_n2_21/Variable:0' shape=(3, 3, 64, 64) dtype=float32> mask
Traceback (most recent call last):
  File "test_fc_aide_ft.py", line 21, in <module>
    denoised_img, psnr, ssim = t_ft.fine_tuning()
  File "/home/bob/FC-AIDE-Keras/core/test_ft.py", line 128, in fine_tuning
    self.model.load_weights('./weights/' + 'sigma' + str(self.noise_sigma) + '.hdf5')
  File "/home/bob/anaconda3/envs/bobsense/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/bob/anaconda3/envs/bobsense/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/bob/anaconda3/envs/bobsense/lib/python3.7/site-packages/keras/engine/saving.py", line 1235, in load_weights_from_hdf5_group
    ' elements.')
ValueError: Layer #0 (named "naide__conv2d__q1_1" in the current model) was found to correspond to layer naide__conv2d__q1_1 in the save file. However the new layer naide__conv2d__q1_1 expects 3 weights, but the saved weights have 2 elements.
``

Is there some problem with the pretrained model?

thanks!

**Comment by ZhaomingKong** [comment]
Same issue here, and it seems the code is problematic when dealing with both grey-scale and color images.

**Comment by XINYUCHENmb95408** [comment]
Layer #0 (named "naide__conv2d__q1_1" in the current model) was found to correspond to layer naide__conv2d__q1_1 in the save file. However the new layer naide__conv2d__q1_1 expects 3 weights, but the saved weights have 2 elements.
The same problem in my computer,it can not test or train, if someone can test please tell me ,thanks.    if any authors can solve this promblem ,please be quick!
